version: "3"

services: 
  app:
    build: .
  restart: on-failure
  networks:
    - app-network
  links: 
    - mongo
    - rabbitmq
  depends_on: 
    - mongo
    - rabbitmq

  mongo:
    image: mongo
    ports: 
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672

networks:
  app-network:
    driver: bridge